# Generated by Django 6.0.6 on 2026-06-25 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('system', models.TextField(blank=True, default='')),
                ('model', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=32)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('mcp_servers', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('packages', models.JSONField(blank=True, default=dict)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('setup_script', models.TextField(blank=True, default='')),
                ('networking_type', models.CharField(choices=[('unrestricted', 'Unrestricted'), ('limited', 'Limited')], default='unrestricted', max_length=16)),
                ('networking_config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('system', models.TextField(blank=True, default='')),
                ('model', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=32)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('mcp_servers', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='fairy.agent')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fairy.environment')),
            ],
            options={
                'db_table': 'agent_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime', models.CharField(max_length=32)),
                ('prompt', models.TextField()),
                ('backend', models.CharField(default='sprites', max_length=32)),
                ('backend_handle', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('runtime_session_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('terminated', 'Terminated')], default='pending', max_length=16)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fairy.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='fairy.environment')),
            ],
            options={
                'db_table': 'agent_sessions',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='fairy.environment'),
        ),
        migrations.CreateModel(
            name='EnvironmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('packages', models.JSONField(blank=True, default=dict)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('setup_script', models.TextField(blank=True, default='')),
                ('networking_type', models.CharField(max_length=16)),
                ('networking_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='fairy.environment')),
            ],
            options={
                'db_table': 'environment_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SessionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('github_repository', 'GitHub Repository')], max_length=32)),
                ('url', models.URLField(max_length=500)),
                ('mount_path', models.CharField(max_length=500)),
                ('encrypted_token', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='fairy.agentsession')),
            ],
            options={
                'db_table': 'session_resources',
            },
        ),
        migrations.CreateModel(
            name='SessionTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='fairy.agentsession')),
            ],
            options={
                'db_table': 'session_turns',
                'ordering': ['session', 'turn_number'],
            },
        ),
        migrations.CreateModel(
            name='AgentSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('output', 'output'), ('stage', 'stage')], default='output', max_length=8)),
                ('stream', models.CharField(blank=True, choices=[('stdout', 'stdout'), ('stderr', 'stderr')], default='', max_length=6)),
                ('data', models.TextField(blank=True, default='')),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(blank=True, choices=[('started', 'started'), ('done', 'done'), ('failed', 'failed')], default='', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fairy.agentsession')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fairy.sessionturn')),
            ],
            options={
                'db_table': 'agent_session_logs',
            },
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('value_encrypted', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_credentials',
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_sessions', models.PositiveIntegerField(blank=True, help_text='Per-user override. Null uses settings.DEFAULT_MAX_CONCURRENT_SESSIONS.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_quotas',
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'name'), name='unique_active_environment_name'),
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('agent', 'version'), name='unique_agent_version'),
        ),
        migrations.AddConstraint(
            model_name='environmentversion',
            constraint=models.UniqueConstraint(fields=('environment', 'version'), name='unique_environment_version'),
        ),
        migrations.AddConstraint(
            model_name='sessionturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_number'), name='unique_session_turn_number'),
        ),
        migrations.AddIndex(
            model_name='agentsessionlog',
            index=models.Index(fields=['session', 'id'], name='agent_sessi_session_049341_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsessionlog',
            index=models.Index(fields=['turn', 'id'], name='agent_sessi_turn_id_c5c936_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercredential',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='unique_user_credential_kind'),
        ),
    ]
